### ISSUE TITLE
live version?

### ISSUE THREAD

**Issue by herohamp** [tjvr/tosh2#1]
Is there a live version using github pages?

**Comment by lightblub** [comment]
It's not hard to get running!

* git clone
* `npm install`
* `npm run build`
* `npm start`
* visit [localhost:8080](http://localhost:8080/app/)

**Comment by herohamp** [comment]
facepalm

**Comment by herohamp** [comment]
ummmm

herohamp:tosh2-master hamptonmoore$ npm install
npm ERR! addLocal Could not install /var/folders/zs/mqf36_413y18v5gj8sn5s5780000gn/T/npm-11586-d3608a2d/git-cache-54fe7a58/a610a82cec1514841a4fd8e2a780a3d03f9a6dab
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3

npm ERR! No name provided in package.json
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hamptonmoore/Downloads/tosh2-master/npm-debug.log
herohamp:tosh2-master hamptonmoore$

**Comment by tjvr** [comment]
@lightblub FWIW the build step isn't necessary at all

**Comment by liam4** [comment]
@herohamp Use [`yarn`](https://yarnpkg.com/) instead.

**Comment by herohamp** [comment]
ok

**Comment by herohamp** [comment]
THANK YOU! now I can view it!

**Comment by tjvr** [comment]
FWIW, since https://github.com/nathan/v2/commit/03984d27f7d1f8ff95098559c46255b13401f552 `npm` works fine:

* `$ git clone --recursive`
* `$ npm install` [although `$ yarn` is still faster!]
* `$ npm start`
* <http://localhost:8080/app/>

...not that I'm expecting you guys to be looking at this right now, of course! :-)
