### ISSUE TITLE
Hacked blocks

### ISSUE THREAD

**Issue by icecream95** [tjvr/tosh2#11]
I use a lot of hacked blocks, such as `set (varname) to 1`, which sets a variable named _the contents_ of `varname` to 1.

In tosh, these blocks are marked red, and I get

> Error saving project: Couldn't compile project

when trying to save.

Can you add support for hacked blocks (i.e. putting something else where an item from a drop-down is expected)?

**Comment by icecream95** [comment]
> Hacked blocks
> Some Scratch projects use “hacked” blocks: these are special blocks made by editing the JSON files by hand, which cannot be made using the normal Scratch editor.
>There are currently no plans to support these. Sorry!

Should've read the docs first.

**Comment by icecream95** [comment]
Just re-opening this to ask why there are "no plans to support [hacked blocks]"?

**Comment by tjvr** [comment]
Mostly because compatibility with Scratch is an important goal, I think.

I don't think this is going to happen. Sorry!

**Comment by icecream95** [comment]
I guess you mean compatibility with the Scratch _editor_, not Scratch itself.

Anyway, I'll probably just fork tosh and add support myself.
