### ISSUE TITLE
Tosh x Ryfelta Project

### ISSUE THREAD

**Issue by aetinx** [tjvr/tosh2#17]
### Tosh x Ryfelta Project

Dear Blob8108, as I don't have any other way of communicating w/ you, I will ask a question here.
Wanna help make this?

It's basically Tosh, but with block category sorted script lines and a much better graphical user interface.

Feel free to contact me on Discord (Speedblocks#0678) or Instagram (@sargentcoding)

Thanks,
Speedblocks

![Synieq OS and Ryfelta (12)](https://user-images.githubusercontent.com/65425469/92941061-e3b8f600-f41d-11ea-972e-453796fe68b6.png)
![Synieq OS and Ryfelta (13)](https://user-images.githubusercontent.com/65425469/92941063-e4518c80-f41d-11ea-9cb5-dd5301a84ad8.png)
![Synieq OS and Ryfelta (14)](https://user-images.githubusercontent.com/65425469/92941065-e4518c80-f41d-11ea-81c2-f41cc6aa1214.png)
![Synieq OS and Ryfelta (15)](https://user-images.githubusercontent.com/65425469/92941066-e4518c80-f41d-11ea-9375-7654c5307c53.png)

**Comment by tjvr** [comment]
I’m afraid I don’t have time to help you, but good luck with your project!

**Comment by aetinx** [comment]
Okay! :)

Visit us at https://www.saco.ml
