### ISSUE TITLE
Project won't run in tosh but it does in scratch

### ISSUE THREAD

**Issue by TheBunnyMan123** [tjvr/tosh2#18]
I have a scratch project (.sb2) and it won't run in tosh but it will in scratch

**Comment by ZenithRogue** [comment]
Does the project have any "hacked" blocks? (Blocks with mismatched or modified input)

**Comment by ZenithRogue** [comment]
Please post the sb2 file here as well for some context

**Comment by TheBunnyMan123** [comment]
[JustAPlatformer.zip](https://github.com/tjvr/tosh2/files/5371795/JustAPlatformer.zip)
Here you go

**Comment by TheBunnyMan123** [comment]
and no

**Comment by truongquangtung2020** [comment]
This is not a bug. Did you read his tips (Tosh)? Read this : https://tosh.blob.codes/help/tips/#:~:text=like%20in%20Scratch!-,Playing%20Projects,Microphone%20(loudness),-Turbo%20mode

**Comment by TheBunnyMan123** [comment]
Can you not revive old posts please?

**Comment by TheBunnyMan123** [comment]
Have you heard of not reviving old posts
