### ISSUE TITLE
/app/JSZip.js does not exist

### ISSUE THREAD

**Issue by lightblub** [tjvr/tosh2#7]
> ReferenceError: JSZip is not defined

Thrown from `tosh.bundle.js` after a Webpack build. This is just a case of OS differences, I believe. I'm assuming that, @tjvr, you're on a Mac here: **on Linux/Windows filenames are case sensitive**, unlike on Macs!

The problem here is that `/build/index.html` has this line:
```html
<script src=/app/JSZip.js></script>
```

Whereas the actual filename is `jszip.js`.

**Comment by tjvr** [comment]
Ah, exciting. I hadn't noticed the difference in case, since I am indeed on a Mac :-)

Would you mind putting in a PR to fix this, and fix `app/index.html` as well if needed? Thanks!

**Comment by tjvr** [comment]
FWIW, I'm not particularly convinced Webpack is the best thing; but that's not really relevant here...

**Comment by TheInitializer** [comment]
Correction: On Windows filenames (and pretty much everything) are case-insensitive. I thought Mac filenames were case-sensitive, but I guess I'm wrong 📦

**Comment by Blaze349** [comment]
You can format your mac to be case sensitive but it might break a lot of things

**Comment by tjvr** [comment]
> it might break a lot of things

Oh, it does! I tried it on my Mac once, it makes Steam and Adobe software very sad...
